name: Integration

on:
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v2
            - name: Install dependencies
              run:  npm install
            - name: Build app
              run: npm run build    

    unit_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v2
            - name: Install dependencies
              run:  npm install
            - name: Run init tests
              run:  npm run test    
            - name: Download Task Definition
              run: |
                aws ecs describe-task-definition --task-definition helloworldtask \ --query taskDefinition>taskDefinition.json

            - name: Read Task Definition
              run: cat task-definition.json



